### ISSUE TITLE
Configure Github Workflow tests

### ISSUE THREAD

**Issue by nimishchaudhari** [nimishchaudhari/OpenMagus#7]
@openhands-agent I noticed that the tests still aren't working, please have a lookl

### 1. **Test Framework and Structure**

- **Choose a Testing Framework:**  
  Use a framework like **pytest** which is popular in Python. It allows you to write simple tests using assert statements and supports fixtures and mocking libraries (such as `unittest.mock` or `pytest-mock`) to simulate external dependencies.

- **Directory Structure:**  
  Organize your tests in a directory (e.g., `tests/`) at the root of your repository. Inside, you might create subdirectories for each core component:
  
  ```
  /tests
    ├── test_coordinator.py
    ├── test_planner.py
    ├── test_knowledge.py
    ├── test_executor.py
    └── test_config.py
  ```

- **Mocking Dependencies:**  
  Use mocking to simulate external systems like Redis, Neo4j, or API calls. For example, if your coordinator uses Redis for session storage, you can mock the Redis client to return preset responses.

---

### 2. **Writing Unit Tests**

For each core component, create tests that cover:
  
- **Functionality Tests:**  
  For example, in `test_coordinator.py`, you might write tests that simulate a task submission, check that the session is stored correctly, and ensure the task is routed to the right agent.

- **Error Handling:**  
  Create tests to simulate exceptions (like missing data or tool failures) and verify that your code handles these gracefully.

- **Integration Points:**  
  Test the interaction between agents where feasible. For instance, a test might simulate a request going from the Coordinator to the Planner and then to the Executor.

**Example Snippet for `test_coordinator.py`:**

```python
import pytest
from unittest.mock import MagicMock
from core.coordinator import CoordinatorAgent

@pytest.fixture
def coordinator():
    # Instantiate your CoordinatorAgent and set up any dependencies as mocks
    agent = CoordinatorAgent()
    agent.redis_client = MagicMock()
    return agent

def test_routing_request(coordinator):
    # Simulate an input request
    request = {"task": "example", "data": "test"}
    # Suppose the coordinator should store the session in redis and route the task
    coordinator.redis_client.set.return_value = True

    response = coordinator.handle_request(request)

    # Assert that the session was stored
    coordinator.redis_client.set.assert_called_once()
    # Assert that the response is as expected
    assert response.get("status") == "task routed"
```

*This test uses `pytest` and Python's built-in `unittest.mock` to simulate external dependencies.*

---

### 3. **Configuring GitHub Actions**

Set up a GitHub Actions workflow file (e.g., `.github/workflows/test.yml`) to run your tests on each push or pull request. Here’s a basic example using Python:

```yaml
name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
```

**Explanation:**

- **Checkout Step:** Retrieves your repository code.  
- **Set Up Python:** Configures the runner with the specified Python version.  
- **Install Dependencies:** Installs your project dependencies and `pytest`.  
- **Run Tests:** Executes `pytest` with options to stop at the first failure and disable warnings, keeping the output concise.

*This workflow will trigger for pushes and pull requests to the `main` branch, ensuring that tests run automatically.*

---

### 4. **Final Considerations**

- **Code Coverage:**  
  Optionally, integrate a coverage tool (e.g., `pytest-cov`) to measure test coverage and post results as part of your CI build.

- **Continuous Integration Benefits:**  
  Automated tests via GitHub Actions ensure that every change is verified against the core components, catching issues early.

- **Documentation:**  
  Add a section in your `README.md` describing how to run tests locally and explaining the GitHub Actions integration.

---

By following this structure, you’ll have a robust set of unit tests that cover your multi-agent framework's core components and automated CI to ensure ongoing reliability. Let me know if you'd like to discuss any part of this in further detail!

---

*References:*  
GitHub Actions [[docs](https://docs.github.com/en/actions)](https://docs.github.com/en/actions) cite60†docs.github.com  
pytest documentation [[here](https://docs.pytest.org/en/stable/)](https://docs.pytest.org/en/stable/) cite0†docs.pytest.org

_Originally posted by @nimishchaudhari in https://github.com/nimishchaudhari/OpenMagus/issues/3#issuecomment-2717436313_
